(() => {
  if(document.getElementById("advancedAnimationPanel"))return;const footer=document.querySelector(".footerbar");if(!footer)return;
  const style=document.createElement("style");style.textContent=`.advanim{padding:18px}.advanim-head{display:flex;justify-content:space-between;gap:10px}.advanim-grid{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:9px}.advanim-box{border:1px solid rgba(127,127,127,.22);border-radius:9px;padding:10px}.advanim-box input,.advanim-box select,.advanim-box textarea{width:100%;box-sizing:border-box;margin-bottom:6px}.advanim-status{font-size:12px;margin-top:8px;white-space:pre-wrap}@media(max-width:950px){.advanim-grid{grid-template-columns:1fr 1fr}}`;
  document.head.appendChild(style);const panel=document.createElement("section");panel.id="advancedAnimationPanel";panel.className="card advanim";
  panel.innerHTML=`<div class="advanim-head"><div><h2>Advanced Animation</h2><p>State · Direction · Event Frame · Hit/Hurt Box</p></div><span>AI NATIVE</span></div><div class="advanim-grid"><div class="advanim-box"><h3>Clip</h3><select id="aaClip"></select><button id="aaRefresh">刷新动画</button></div><div class="advanim-box"><h3>事件帧</h3><input id="aaEventFrame" type="number" min="0" value="0"/><input id="aaEventName" value="footstep"/><button id="aaAddEvent">添加 Event</button></div><div class="advanim-box"><h3>Frame Box</h3><select id="aaBoxType"><option value="hit">Hit</option><option value="hurt">Hurt</option><option value="interaction">Interaction</option></select><input id="aaBoxFrame" type="number" min="0" value="0"/><div style="display:grid;grid-template-columns:1fr 1fr;gap:4px"><input id="aaBoxX" value="0.2"/><input id="aaBoxY" value="0.2"/><input id="aaBoxW" value="0.6"/><input id="aaBoxH" value="0.6"/></div><button id="aaAddBox">添加 Box</button></div><div class="advanim-box"><h3>State / Direction Set</h3><input id="aaSetName" value="player"/><textarea id="aaStates" rows="3" placeholder="idle=anim_xxx\nwalk=anim_yyy"></textarea><input id="aaDefault" value="idle" placeholder="default state"/><textarea id="aaDirections" rows="2" placeholder="up=anim_up\ndown=anim_down"></textarea><button id="aaCreateSet">创建 State Set</button><input id="aaSetIds" placeholder="animset_xxx"/><select id="aaEngine"><option value="generic">Generic</option><option value="godot4">Godot 4</option><option value="unity2d">Unity 2D</option></select><button id="aaExport">导出高级动画</button><a id="aaDownload" class="hidden">下载</a></div></div><div id="aaStatus" class="advanim-status">高级动画引用现有 anim_* Clip，不复制帧素材。</div>`;footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id);const status=t=>$("aaStatus").textContent=t;async function json(url,opts){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw new Error(d.detail||r.statusText);return d;}
  function kv(text){const out={};text.split(/\n|,/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const i=line.indexOf("=");if(i>0)out[line.slice(0,i).trim()]=line.slice(i+1).trim();});return out;}
  async function refresh(){const clips=await json("/api/v1/library/animations");$("aaClip").innerHTML=clips.map(c=>`<option value="${c.id}">${c.name} · ${c.frame_asset_ids.length}f</option>`).join("");status(`${clips.length} 个基础 Animation Clip`);}$("aaRefresh").onclick=()=>refresh().catch(e=>status(e.message));
  $("aaAddEvent").onclick=async()=>{const clip_id=$("aaClip").value;if(!clip_id)return status("没有可用 Clip");try{const d=await json("/api/v1/library/advanced-animation/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clip_id,frame_index:Number($("aaEventFrame").value||0),name:$("aaEventName").value.trim()||"event",payload:{}})});status(`Event ${d.id} 已加入 frame ${d.frame_index}`);}catch(e){status(e.message);}};
  $("aaAddBox").onclick=async()=>{const clip_id=$("aaClip").value;if(!clip_id)return status("没有可用 Clip");try{const d=await json("/api/v1/library/advanced-animation/frame-boxes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clip_id,frame_index:Number($("aaBoxFrame").value||0),box_type:$("aaBoxType").value,x:Number($("aaBoxX").value),y:Number($("aaBoxY").value),width:Number($("aaBoxW").value),height:Number($("aaBoxH").value)})});status(`${d.box_type} Box ${d.id} 已加入 frame ${d.frame_index}`);}catch(e){status(e.message);}};
  $("aaCreateSet").onclick=async()=>{const states=kv($("aaStates").value);try{const d=await json("/api/v1/library/advanced-animation/state-sets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("aaSetName").value.trim()||"animation_set",states,default_state:$("aaDefault").value.trim(),directions:kv($("aaDirections").value),transitions:[]})});$("aaSetIds").value=d.id;status(`State Set 已创建：${d.id}`);}catch(e){status(e.message);}};
  $("aaExport").onclick=async()=>{const state_set_ids=$("aaSetIds").value.split(",").map(x=>x.trim()).filter(Boolean);if(!state_set_ids.length)return status("请输入 State Set ID");try{const d=await json("/api/v1/library/advanced-animation/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({state_set_ids,engine:$("aaEngine").value})});const a=$("aaDownload");a.href=d.download_url;a.classList.remove("hidden");a.textContent=`下载 ${d.export_id}`;status(`高级动画导出完成：${d.state_set_count} sets`);}catch(e){status(e.message);}};
  refresh().catch(()=>{});
})();
