(() => {
  if (document.getElementById("assetPackSystemPanel")) return;
  const footer = document.querySelector(".footerbar");
  if (!footer) return;
  const style = document.createElement("style");
  style.textContent = `.aps-panel{padding:18px}.aps-grid{display:grid;grid-template-columns:repeat(3,minmax(260px,1fr));gap:12px}.aps-box{border:1px solid rgba(127,127,127,.22);border-radius:10px;padding:12px}.aps-box label{display:flex;flex-direction:column;gap:4px;margin:7px 0;font-size:11px}.aps-box input,.aps-box textarea,.aps-box select{width:100%;box-sizing:border-box}.aps-list{max-height:260px;overflow:auto;font-size:12px}.aps-row{padding:7px 0;border-bottom:1px solid rgba(127,127,127,.12)}.aps-status{white-space:pre-wrap;font-size:12px;margin-top:10px}@media(max-width:1000px){.aps-grid{grid-template-columns:1fr}}`;
  document.head.appendChild(style);
  const panel = document.createElement("section");
  panel.id="assetPackSystemPanel"; panel.className="card aps-panel";
  panel.innerHTML=`<div style="display:flex;justify-content:space-between"><div><h2 style="margin:0">Asset Pack System</h2><p style="margin:4px 0 12px;opacity:.72">Version · Dependency · Install Lock · Update · Export</p></div><span>AI NATIVE</span></div>
  <div class="aps-grid">
    <div class="aps-box"><h3>Create Pack</h3><label>Name<input id="apsName" value="my_pack"></label><label>Description<textarea id="apsDesc" rows="3"></textarea></label><label>Asset IDs<input id="apsAssets" placeholder="selected assets or comma list"></label><label>Dependencies<input id="apsDeps" placeholder="pack_xxx@1.0.0,pack_yyy"></label><button id="apsCreate">Create from selected assets</button></div>
    <div class="aps-box"><h3>Release / Install</h3><label>Pack<select id="apsPack"></select></label><label>Version<input id="apsVersion" value="1.0.0"></label><label>Release notes<input id="apsNotes"></label><div style="display:flex;gap:6px;flex-wrap:wrap"><button id="apsRelease">Release</button><button id="apsInstall">Install</button><button id="apsUninstall">Uninstall</button><button id="apsExport">Export</button></div><a id="apsDownload" class="hidden" style="display:inline-block;margin-top:8px">Download</a></div>
    <div class="aps-box"><h3>Installed / Updates</h3><button id="apsRefresh">Refresh</button><div id="apsInstalled" class="aps-list"></div><div id="apsUpdates" class="aps-list"></div></div>
  </div><div id="apsStatus" class="aps-status">Pack releases freeze Asset Library versions.</div>`;
  footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id); const status=t=>{$("apsStatus").textContent=t;};
  const csv=v=>v.split(",").map(x=>x.trim()).filter(Boolean);
  function selectedAssetIds(){const ids=[...document.querySelectorAll(".library-card-select:checked")].map(i=>i.closest(".library-card")?.dataset.assetId).filter(Boolean);return [...new Set(ids.length?ids:csv($("apsAssets").value))];}
  function deps(){return csv($("apsDeps").value).map(raw=>{const [pack_id,version]=raw.split("@");return {pack_id,version:version||null};});}
  async function jf(url,opt={}){const r=await fetch(url,opt); if(r.status===204)return null; const d=await r.json(); if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d;}
  async function refresh(){const packs=await jf("/api/v1/library/package-system/packs");$("apsPack").innerHTML=packs.map(p=>`<option value="${p.id}">${p.name}${p.latest_version?` · ${p.latest_version}`:""}</option>`).join("");const installed=await jf("/api/v1/library/package-system/installed");$("apsInstalled").innerHTML='<b>Installed</b>'+installed.map(i=>`<div class="aps-row">${i.pack_id} @ ${i.version}<br><small>${Object.keys(i.lock.assets||{}).length} locked assets</small></div>`).join("");const updates=await jf("/api/v1/library/package-system/updates");$("apsUpdates").innerHTML='<b>Updates</b>'+updates.map(u=>`<div class="aps-row">${u.pack_id}: ${u.installed_version} → ${u.latest_version} ${u.update_available?'⬆':''}</div>`).join("");}
  $("apsCreate").onclick=async()=>{try{const ids=selectedAssetIds(); if(!ids.length)throw new Error("Select assets first"); const data=await jf("/api/v1/library/package-system/packs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("apsName").value,description:$("apsDesc").value,asset_ids:ids,dependencies:deps()})});status(`Created ${data.id}`);await refresh();$("apsPack").value=data.id;}catch(e){status(e.message)}};
  $("apsRelease").onclick=async()=>{try{const id=$("apsPack").value;const d=await jf(`/api/v1/library/package-system/packs/${id}/releases`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:$("apsVersion").value,notes:$("apsNotes").value})});status(`Released ${d.pack_id}@${d.version}`);await refresh();}catch(e){status(e.message)}};
  $("apsInstall").onclick=async()=>{try{const id=$("apsPack").value;const d=await jf(`/api/v1/library/package-system/packs/${id}/install`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:$("apsVersion").value||null})});status(`Installed ${d.pack_id}@${d.version}`);await refresh();}catch(e){status(e.message)}};
  $("apsUninstall").onclick=async()=>{try{const id=$("apsPack").value;await jf(`/api/v1/library/package-system/packs/${id}/install`,{method:"DELETE"});status(`Uninstalled ${id}; Asset Library files were not deleted.`);await refresh();}catch(e){status(e.message)}};
  $("apsExport").onclick=async()=>{try{const id=$("apsPack").value;const d=await jf(`/api/v1/library/package-system/packs/${id}/export`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version:$("apsVersion").value||null})});const a=$("apsDownload");a.href=d.download_url;a.textContent=`Download ${d.pack_id}@${d.version}`;a.classList.remove("hidden");status(`Export ready: ${d.export_id}`);}catch(e){status(e.message)}};
  $("apsRefresh").onclick=()=>refresh().catch(e=>status(e.message)); refresh().catch(()=>{});
})();
