(() => {
  if (document.getElementById("assetIntelligencePanel")) return;
  const footer=document.querySelector(".footerbar"); if(!footer)return;
  const style=document.createElement("style"); style.textContent=`.intel-panel{padding:18px}.intel-head{display:flex;justify-content:space-between;gap:10px}.intel-actions{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.intel-report{display:grid;grid-template-columns:180px 1fr 1fr;gap:10px;border:1px solid rgba(127,127,127,.22);border-radius:9px;padding:10px}.intel-score{font-size:30px;font-weight:800}.intel-small{font-size:12px;opacity:.75}.intel-tags{display:flex;gap:4px;flex-wrap:wrap}.intel-tag{padding:2px 6px;border-radius:99px;background:rgba(100,160,255,.15);font-size:11px}@media(max-width:800px){.intel-report{grid-template-columns:1fr}}`;
  document.head.appendChild(style);
  const panel=document.createElement("section");panel.id="assetIntelligencePanel";panel.className="card intel-panel";
  panel.innerHTML=`<div class="intel-head"><div><h2>Asset Intelligence</h2><p>自动分类 · 标签建议 · 质量体检 · 重复检测</p></div><span>AI NATIVE</span></div><div class="intel-actions"><button id="intelAnalyze">分析当前素材</button><button id="intelBulk">批量分析勾选素材</button><button id="intelApply" disabled>应用当前建议</button></div><div id="intelReports"></div><div id="intelStatus" class="intel-small">分析不会修改素材；只有“应用当前建议”才写入分类/标签。</div>`;
  footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id);let reports=[];let current=null;const status=t=>$("intelStatus").textContent=t;
  async function json(url,opts){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw new Error(d.detail||r.statusText);return d;}
  function currentId(){return document.querySelector(".library-card.selected")?.dataset.assetId||null;}
  function checked(){return [...document.querySelectorAll(".library-card-select:checked")].map(x=>x.closest(".library-card")?.dataset.assetId).filter(Boolean);}
  function render(){$("intelReports").innerHTML=reports.map((r,i)=>`<div class="intel-report" data-i="${i}"><div><div class="intel-score">${Math.round(r.quality_score*100)}</div><div class="intel-small">Quality Score</div><button class="intelSelect">选择报告</button></div><div><b>${r.suggested_category}</b><div>${r.suggested_subcategory||"-"}</div><div class="intel-tags">${r.suggested_tags.map(t=>`<span class="intel-tag">${t}</span>`).join("")}</div></div><div><b>问题</b><div class="intel-small">${r.issues.join(" · ")||"未发现明显问题"}</div><b>疑似重复</b><div class="intel-small">${r.duplicate_candidates.map(d=>`${d.name} ${Math.round(d.visual_similarity*100)}%`).join(" · ")||"无"}</div></div></div>`).join("");}
  $("intelAnalyze").onclick=async()=>{const id=currentId();if(!id)return status("请先选择素材。");try{current=await json(`/api/v1/library/intelligence/assets/${id}/analyze`,{method:"POST"});reports=[current];render();$("intelApply").disabled=false;status("分析完成，尚未修改素材。");}catch(e){status(e.message);}};
  $("intelBulk").onclick=async()=>{const ids=checked();if(!ids.length)return status("请先勾选素材。");try{reports=await json("/api/v1/library/intelligence/analyze-bulk",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset_ids:ids,duplicate_threshold:.9})});current=reports[0]||null;render();$("intelApply").disabled=!current;status(`已分析 ${reports.length} 个素材，未写入修改。`);}catch(e){status(e.message);}};
  $("intelReports").onclick=e=>{const row=e.target.closest("[data-i]");if(row&&e.target.closest(".intelSelect")){current=reports[Number(row.dataset.i)];$("intelApply").disabled=false;status(`已选择报告：${current.asset_id}`);}};
  $("intelApply").onclick=async()=>{if(!current)return;try{const asset=await json(`/api/v1/library/intelligence/assets/${current.asset_id}/apply`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({apply_category:true,apply_subcategory:true,add_tags:true,report:current})});status(`已应用：${asset.name} → ${asset.category}`);window.GameCreaterAssetLibrary?.refresh?.();}catch(e){status(e.message);}};
})();
