(() => {
  if (document.getElementById("engineSyncPanel")) return;
  const footer = document.querySelector(".footerbar");
  if (!footer) return;
  const style=document.createElement("style");
  style.textContent=`.es-panel{padding:18px}.es-grid{display:grid;grid-template-columns:320px 1fr;gap:12px}.es-box{border:1px solid rgba(127,127,127,.22);border-radius:10px;padding:12px}.es-box label{display:flex;flex-direction:column;gap:4px;margin:7px 0;font-size:11px}.es-box input,.es-box select{width:100%;box-sizing:border-box}.es-files{max-height:340px;overflow:auto;font-size:11px}.es-row{display:grid;grid-template-columns:80px 1fr;gap:7px;padding:5px 0;border-bottom:1px solid rgba(127,127,127,.12)}.es-status{white-space:pre-wrap;font-size:12px;margin-top:10px}@media(max-width:900px){.es-grid{grid-template-columns:1fr}}`;
  document.head.appendChild(style);
  const panel=document.createElement("section");panel.id="engineSyncPanel";panel.className="card es-panel";
  panel.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px"><div><h2 style="margin:0">Engine Sync</h2><p style="margin:4px 0 12px;opacity:.72">Incremental Godot / Unity project sync · managed namespace only</p></div><span>LOCAL · AI NATIVE</span></div>
  <div class="es-grid"><div class="es-box"><h3>Profile</h3><label>Name<input id="esName" value="local_project"></label><label>Engine<select id="esEngine"><option value="godot4">Godot 4</option><option value="unity2d">Unity 2D</option></select></label><label>Local project root<input id="esRoot" placeholder="C:\\Projects\\MyGame"></label><label>Asset IDs<input id="esAssets" placeholder="uses selected Library assets first"></label><button id="esCreate">Create profile</button><label>Existing profile<select id="esProfile"></select></label><div style="display:flex;gap:6px;flex-wrap:wrap"><button id="esPlan">Plan</button><button id="esSync">Sync</button><button id="esRefresh">Refresh</button></div><p style="font-size:11px;opacity:.68">Godot writes only GameCreaterAssets/. Unity writes only Assets/GameCreater/. Run the backend locally when using project paths.</p></div>
  <div class="es-box"><h3>Sync Plan</h3><div id="esSummary">No plan.</div><div id="esFiles" class="es-files"></div><button id="esPrune" disabled>Prune reported stale files</button></div></div><div id="esStatus" class="es-status">Sync never deletes stale files automatically.</div>`;
  footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id);let currentPlan=null;const status=t=>{$("esStatus").textContent=t;};
  const csv=v=>v.split(",").map(x=>x.trim()).filter(Boolean);
  function selectedAssetIds(){const ids=[...document.querySelectorAll(".library-card-select:checked")].map(i=>i.closest(".library-card")?.dataset.assetId).filter(Boolean);return [...new Set(ids.length?ids:csv($("esAssets").value))];}
  async function jf(url,opt={}){const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d;}
  async function refresh(selected=null){const profiles=await jf("/api/v1/library/engine-sync/profiles");$("esProfile").innerHTML=profiles.map(p=>`<option value="${p.id}">${p.name} · ${p.engine}</option>`).join("");if(selected)$("esProfile").value=selected;}
  function renderPlan(plan){currentPlan=plan;$("esSummary").textContent=`${plan.engine} · add ${plan.add_count} · update ${plan.update_count} · unchanged ${plan.unchanged_count} · stale ${plan.stale_paths.length}`;$("esFiles").innerHTML=plan.files.map(f=>`<div class="es-row"><b>${f.action}</b><span>${f.relative_path}</span></div>`).join("");$("esPrune").disabled=!plan.stale_paths.length;}
  $("esCreate").onclick=async()=>{try{const ids=selectedAssetIds();if(!ids.length)throw new Error("Select Asset Library items first");const p=await jf("/api/v1/library/engine-sync/profiles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("esName").value,engine:$("esEngine").value,project_root:$("esRoot").value,asset_ids:ids})});await refresh(p.id);status(`Profile ${p.id}\nManaged root: ${p.managed_root}`);}catch(e){status(e.message)}};
  $("esPlan").onclick=async()=>{try{const id=$("esProfile").value;if(!id)throw new Error("Create/select a profile");renderPlan(await jf(`/api/v1/library/engine-sync/profiles/${id}/plan`));status("Plan calculated. Stale files are only reported.");}catch(e){status(e.message)}};
  $("esSync").onclick=async()=>{try{const id=$("esProfile").value;if(!id)throw new Error("Create/select a profile");const r=await jf(`/api/v1/library/engine-sync/profiles/${id}/sync`,{method:"POST"});status(`Synced ${r.copied.length} files · unchanged ${r.unchanged.length}\n${r.manifest_path}`);renderPlan(await jf(`/api/v1/library/engine-sync/profiles/${id}/plan`));}catch(e){status(e.message)}};
  $("esPrune").onclick=async()=>{try{if(!currentPlan?.stale_paths?.length)return;const id=$("esProfile").value;const r=await jf(`/api/v1/library/engine-sync/profiles/${id}/stale`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({relative_paths:currentPlan.stale_paths})});status(`Pruned ${r.removed.length} managed stale files.`);renderPlan(await jf(`/api/v1/library/engine-sync/profiles/${id}/plan`));}catch(e){status(e.message)}};
  $("esRefresh").onclick=()=>refresh().catch(e=>status(e.message));refresh().catch(()=>{});
})();
