(() => {
  if (document.getElementById("projectWorkspacePanel")) return;
  const footer=document.querySelector(".footerbar"); if(!footer)return;
  const style=document.createElement("style");style.textContent=`.pw-panel{padding:18px}.pw-grid{display:grid;grid-template-columns:300px 1fr 300px;gap:12px}.pw-box{border:1px solid rgba(127,127,127,.22);border-radius:10px;padding:12px}.pw-box label{display:flex;flex-direction:column;gap:4px;margin:7px 0;font-size:11px}.pw-box input,.pw-box select{width:100%;box-sizing:border-box}.pw-list{max-height:360px;overflow:auto;font-size:11px}.pw-row{padding:7px 0;border-bottom:1px solid rgba(127,127,127,.12)}.pw-status{white-space:pre-wrap;font-size:12px;margin-top:10px}@media(max-width:1050px){.pw-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);
  const panel=document.createElement("section");panel.id="projectWorkspacePanel";panel.className="card pw-panel";panel.innerHTML=`<div style="display:flex;justify-content:space-between"><div><h2 style="margin:0">Project Workspace</h2><p style="margin:4px 0 12px;opacity:.72">Project asset usage · Version Lock · Dependency Graph</p></div><span>AI NATIVE</span></div><div class="pw-grid"><div class="pw-box"><h3>Project</h3><label>Name<input id="pwName" value="my_game"></label><label>Engine<select id="pwEngine"><option value="generic">Generic</option><option value="godot4">Godot 4</option><option value="unity2d">Unity 2D</option></select></label><button id="pwCreate">Create</button><label>Workspace<select id="pwSelect"></select></label><button id="pwRefresh">Refresh</button><hr><h3>Add selected assets</h3><label>Role<input id="pwRole" placeholder="environment / character / ui"></label><label style="flex-direction:row;align-items:center"><input id="pwLock" type="checkbox" checked style="width:auto"> Lock current version</label><button id="pwAdd">Add selected Asset Library items</button></div><div class="pw-box"><h3>Resolved Assets</h3><div id="pwSummary">No workspace.</div><div id="pwAssets" class="pw-list"></div></div><div class="pw-box"><h3>Dependency</h3><label>Source Asset ID<input id="pwDepSource"></label><label>Depends on Asset ID<input id="pwDepTarget"></label><label>Reason<input id="pwDepReason"></label><button id="pwDepAdd">Add dependency</button><div id="pwDeps" class="pw-list"></div><hr><button id="pwExport">Export project lock</button><a id="pwDownload" class="hidden" style="display:inline-block;margin-top:8px">Download</a></div></div><div id="pwStatus" class="pw-status">Locked assets do not follow later Asset Library versions until explicitly changed.</div>`;footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id);let current=null;const status=t=>{$("pwStatus").textContent=t;};
  async function jf(url,opt={}){const r=await fetch(url,opt);const d=await r.json();if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d;}
  function selectedAssetIds(){return [...new Set([...document.querySelectorAll(".library-card-select:checked")].map(i=>i.closest(".library-card")?.dataset.assetId).filter(Boolean))];}
  async function refresh(selectId=null){const list=await jf("/api/v1/library/project-workspaces");$("pwSelect").innerHTML=list.map(p=>`<option value="${p.id}">${p.name} · ${p.engine}</option>`).join("");if(selectId)$("pwSelect").value=selectId;const id=$("pwSelect").value;if(id)await load(id);}
  async function load(id){current=await jf(`/api/v1/library/project-workspaces/${id}`);const resolved=await jf(`/api/v1/library/project-workspaces/${id}/resolve`);$("pwSummary").textContent=`${current.name} · ${resolved.assets.length} assets · drift ${resolved.drift_count}`;$("pwAssets").innerHTML=resolved.assets.map(a=>`<div class="pw-row"><b>${a.name}</b> · ${a.role||"no role"}<br>${a.asset_id}<br>resolved v${a.resolved_version} / active v${a.active_version} ${a.drifted?'⚠ DRIFT':''}<br><button data-follow="${a.asset_id}">Follow Active</button> <button data-lock="${a.asset_id}">Lock Current</button></div>`).join("");$("pwDeps").innerHTML=current.dependencies.map(d=>`<div class="pw-row">${d.source_asset_id}<br>↓ depends on<br>${d.target_asset_id}<br><small>${d.reason||""}</small></div>`).join("");$("pwAssets").querySelectorAll("[data-follow]").forEach(btn=>btn.onclick=()=>setMode(btn.dataset.follow,true));$("pwAssets").querySelectorAll("[data-lock]").forEach(btn=>btn.onclick=()=>setMode(btn.dataset.lock,false));}
  async function setMode(assetId,follow){try{await jf(`/api/v1/library/project-workspaces/${current.id}/assets/${assetId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({follow_active:follow})});await load(current.id);status(follow?` ${assetId} now follows active version.`:`${assetId} locked to current version.`);}catch(e){status(e.message)}}
  $("pwCreate").onclick=async()=>{try{const p=await jf("/api/v1/library/project-workspaces",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("pwName").value,engine:$("pwEngine").value})});await refresh(p.id);status(`Created ${p.id}`);}catch(e){status(e.message)}};
  $("pwSelect").onchange=e=>e.target.value&&load(e.target.value).catch(err=>status(err.message));$("pwRefresh").onclick=()=>refresh().catch(e=>status(e.message));
  $("pwAdd").onclick=async()=>{try{if(!current)throw new Error("Select a workspace");const ids=selectedAssetIds();if(!ids.length)throw new Error("Select Asset Library items first");await jf(`/api/v1/library/project-workspaces/${current.id}/assets`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset_ids:ids,lock_to_current:$("pwLock").checked,role:$("pwRole").value})});await load(current.id);status(`Added ${ids.length} assets.`);}catch(e){status(e.message)}};
  $("pwDepAdd").onclick=async()=>{try{if(!current)throw new Error("Select a workspace");await jf(`/api/v1/library/project-workspaces/${current.id}/dependencies`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source_asset_id:$("pwDepSource").value,target_asset_id:$("pwDepTarget").value,reason:$("pwDepReason").value})});await load(current.id);status("Dependency added.");}catch(e){status(e.message)}};
  $("pwExport").onclick=async()=>{try{if(!current)throw new Error("Select a workspace");const d=await jf(`/api/v1/library/project-workspaces/${current.id}/export`,{method:"POST"});const a=$("pwDownload");a.href=d.download_url;a.textContent="Download project lock";a.classList.remove("hidden");status(`Export ready: ${d.export_id}`);}catch(e){status(e.message)}};refresh().catch(()=>{});
})();
