(() => {
  if (document.getElementById("spriteAtlasPanel")) return;
  const footer=document.querySelector(".footerbar"); if(!footer)return;
  const style=document.createElement("style");style.textContent=`.atlas-panel{padding:18px}.atlas-head{display:flex;justify-content:space-between;gap:10px}.atlas-grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:8px;margin:10px 0}.atlas-grid label{display:flex;flex-direction:column;gap:4px;font-size:11px}.atlas-grid input,.atlas-grid select{width:100%;box-sizing:border-box}.atlas-actions{display:flex;gap:8px;align-items:center}.atlas-status{font-size:12px;margin-top:8px;white-space:pre-wrap}@media(max-width:800px){.atlas-grid{grid-template-columns:1fr 1fr}}`;
  document.head.appendChild(style);
  const panel=document.createElement("section");panel.id="spriteAtlasPanel";panel.className="card atlas-panel";
  panel.innerHTML=`<div class="atlas-head"><div><h2>Sprite / Atlas Pipeline</h2><p>Trim · MaxRects · Padding · POT · Godot AtlasTexture · Unity Multiple Sprite</p></div><span>AI NATIVE</span></div><div class="atlas-grid"><label>Atlas 名<input id="atlasName" value="game_atlas"/></label><label>目标<select id="atlasEngine"><option value="generic">Generic</option><option value="godot4">Godot 4</option><option value="unity2d">Unity 2D</option></select></label><label>Max Width<input id="atlasW" type="number" value="2048"/></label><label>Max Height<input id="atlasH" type="number" value="2048"/></label><label>Padding<input id="atlasPadding" type="number" value="2" min="0" max="64"/></label><label><span>Trim</span><input id="atlasTrim" type="checkbox" checked/></label><label><span>Power of Two</span><input id="atlasPot" type="checkbox" checked/></label></div><div class="atlas-actions"><button id="atlasBuild">打包勾选素材</button><a id="atlasDownload" class="hidden">下载 Atlas</a></div><div id="atlasStatus" class="atlas-status">在 Asset Library 勾选要进入同一图集的素材。</div>`;
  footer.insertAdjacentElement("beforebegin",panel);
  const $=id=>document.getElementById(id);const status=t=>$("atlasStatus").textContent=t;
  function selected(){const ids=[...document.querySelectorAll(".library-card-select:checked")].map(x=>x.closest(".library-card")?.dataset.assetId).filter(Boolean);const cur=document.querySelector(".library-card.selected")?.dataset.assetId;if(!ids.length&&cur)ids.push(cur);return [...new Set(ids)];}
  async function json(url,opts){const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw new Error(d.detail||r.statusText);return d;}
  $("atlasBuild").onclick=async()=>{const asset_ids=selected();if(!asset_ids.length)return status("请先勾选素材。");try{status(`正在用 MaxRects 打包 ${asset_ids.length} 个素材…`);const data=await json("/api/v1/library/atlases",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("atlasName").value.trim()||"atlas",asset_ids,engine:$("atlasEngine").value,max_width:Number($("atlasW").value||2048),max_height:Number($("atlasH").value||2048),padding:Number($("atlasPadding").value||0),trim_transparent:$("atlasTrim").checked,power_of_two:$("atlasPot").checked})});const a=$("atlasDownload");a.href=data.download_url;a.classList.remove("hidden");a.textContent=`下载 ${data.name}`;status(`Atlas ${data.atlas_id}\n${data.sprite_count} sprites · ${data.page_count} page(s) · ${data.engine}`);}catch(e){status(`Atlas 失败：${e.message}`);}};
})();
