from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path

from app.models import AssetRecord, SceneManifest
from app.services.scene_store import SceneStore


class GodotExporter:
    """Export one normalized Game Creater scene as a self-contained Godot 4 project.

    The exporter does not require the Godot binary. Each extracted RGBA asset is
    copied into the project and instantiated as a Sprite2D. Sprite node origins
    are placed at the bottom-center of their source bboxes and the texture is
    offset upward, so the visual placement remains pixel-accurate while Godot's
    y_sort_enabled can use the object bottom as a practical painter-order anchor.
    """

    def __init__(self, workspace: str | Path, export_dir: str | Path) -> None:
        self.workspace = Path(workspace)
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(parents=True, exist_ok=True)
        self.store = SceneStore(self.workspace)

    def export(self, scene_id: str) -> Path:
        manifest = self.store.load(scene_id)
        scene_dir = self.workspace / scene_id
        archive_path = self.export_dir / f"game_creater_{scene_id}_godot4.zip"

        project_text = self._project_godot(manifest)
        scene_text = self._scene_tscn(manifest)
        readme_text = self._project_readme(manifest)
        metadata = self._metadata(manifest)

        with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("project.godot", project_text)
            archive.writestr("scenes/generated_scene.tscn", scene_text)
            archive.writestr(
                "metadata/scene.json",
                json.dumps(metadata, ensure_ascii=False, indent=2),
            )
            archive.writestr("README_GAME_CREATER.txt", readme_text)

            for asset in manifest.assets:
                source_asset = scene_dir / asset.image
                if not source_asset.is_file():
                    raise ValueError(f"Asset image is missing for {asset.id}: {source_asset}")
                archive.write(source_asset, arcname=self._godot_asset_path(asset))

            if manifest.source_file:
                source_reference = scene_dir / manifest.source_file
                if source_reference.is_file():
                    suffix = source_reference.suffix.lower() or ".png"
                    archive.write(source_reference, arcname=f"reference/source{suffix}")

        return archive_path

    def _project_godot(self, manifest: SceneManifest) -> str:
        project_name = self._godot_string(f"Game Creater {manifest.scene_id}")
        return (
            "; Engine configuration file.\n"
            "; Generated by Game Creater.\n\n"
            "config_version=5\n\n"
            "[application]\n\n"
            f'config/name="{project_name}"\n'
            'run/main_scene="res://scenes/generated_scene.tscn"\n\n'
            "[display]\n\n"
            f"window/size/viewport_width={manifest.width}\n"
            f"window/size/viewport_height={manifest.height}\n\n"
            "[rendering]\n\n"
            'renderer/rendering_method="gl_compatibility"\n'
            'renderer/rendering_method.mobile="gl_compatibility"\n'
        )

    def _scene_tscn(self, manifest: SceneManifest) -> str:
        lines: list[str] = ["[gd_scene format=3]", ""]
        resource_ids: dict[str, str] = {}

        for index, asset in enumerate(manifest.assets, start=1):
            resource_id = f"{index}_asset"
            resource_ids[asset.id] = resource_id
            path = self._godot_asset_path(asset)
            lines.append(
                f'[ext_resource type="Texture2D" path="res://{self._godot_string(path)}" id="{resource_id}"]'
            )

        if manifest.assets:
            lines.append("")

        lines.extend(
            [
                '[node name="GeneratedScene" type="Node2D"]',
                "y_sort_enabled = true",
                "",
            ]
        )

        # Stable source order is kept for objects whose Y positions are equal.
        ordered_assets = sorted(
            enumerate(manifest.assets),
            key=lambda pair: (pair[1].bbox.y2, pair[0]),
        )
        for _, asset in ordered_assets:
            width = asset.bbox.x2 - asset.bbox.x1
            height = asset.bbox.y2 - asset.bbox.y1
            center_x = (asset.bbox.x1 + asset.bbox.x2) / 2.0
            bottom_y = float(asset.bbox.y2)
            offset_y = -height / 2.0
            node_name = self._node_name(asset)
            resource_id = resource_ids[asset.id]

            lines.append(
                f'[node name="{self._godot_string(node_name)}" type="Sprite2D" parent="."]'
            )
            lines.append(f"position = Vector2({self._number(center_x)}, {self._number(bottom_y)})")
            lines.append(f"offset = Vector2(0, {self._number(offset_y)})")
            lines.append(f'texture = ExtResource("{resource_id}")')
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    def _metadata(self, manifest: SceneManifest) -> dict:
        data = manifest.model_dump()
        data["engine_export"] = {
            "engine": "godot",
            "target": "Godot 4",
            "main_scene": "res://scenes/generated_scene.tscn",
            "coordinate_system": "source-image pixels; origin top-left",
            "sprite_anchor": "bbox bottom-center",
            "y_sort_enabled": True,
        }
        data["assets"] = [
            {
                **asset.model_dump(),
                "godot_texture": f"res://{self._godot_asset_path(asset)}",
                "godot_node": self._node_name(asset),
                "godot_position": [
                    (asset.bbox.x1 + asset.bbox.x2) / 2.0,
                    float(asset.bbox.y2),
                ],
            }
            for asset in manifest.assets
        ]
        return data

    def _project_readme(self, manifest: SceneManifest) -> str:
        return f"""Game Creater -> Godot 4 export

Scene ID: {manifest.scene_id}
Source size: {manifest.width} x {manifest.height}
Assets: {len(manifest.assets)}

Open this folder as a Godot project. The main scene is:
  res://scenes/generated_scene.tscn

Placement:
- 1 source image pixel = 1 Godot 2D unit/pixel at default scale.
- Sprite2D node positions use each asset bbox bottom-center.
- Sprite texture offsets preserve the original image placement.
- The root Node2D has y_sort_enabled=true, so object bottoms provide a useful
  first-pass painter order for ground-based 2D scenes.

Not generated yet:
- collision shapes
- navigation
- gameplay scripts
- true depth/occlusion reconstruction

The retained source image is included under reference/ for comparison only and
is not instantiated in the generated scene, avoiding duplicated artwork.
"""

    @staticmethod
    def _godot_asset_path(asset: AssetRecord) -> str:
        return f"assets/{asset.id}.png"

    @classmethod
    def _node_name(cls, asset: AssetRecord) -> str:
        suffix = re.sub(r"[^A-Za-z0-9_]+", "_", asset.label).strip("_")
        suffix = suffix[:40]
        base = asset.id.replace("asset_", "Asset_")
        return f"{base}_{suffix}" if suffix else base

    @staticmethod
    def _godot_string(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")

    @staticmethod
    def _number(value: float) -> str:
        if float(value).is_integer():
            return str(int(value))
        return f"{value:.4f}".rstrip("0").rstrip(".")
