#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VENV_DIR="${BIREFNET_VENV_DIR:-$HOME/.local/share/game_creater/birefnet-venv}"
ENV_FILE="${BIREFNET_ENV_FILE:-$HOME/.config/game_creater/birefnet.env}"
MODEL_ID="${BIREFNET_MODEL_ID:-ZhengPeng7/BiRefNet_HR-matting}"
DEVICE="${BIREFNET_DEVICE:-auto}"
INPUT_SIZE="${BIREFNET_INPUT_SIZE:-1024}"

python - <<'PY'
import sys
if sys.version_info < (3, 10):
    raise SystemExit(f"Python >=3.10 is required, got {sys.version.split()[0]}")
print(f"python={sys.version.split()[0]}")
PY

mkdir -p "$(dirname "$VENV_DIR")" "$(dirname "$ENV_FILE")"
if [ ! -x "$VENV_DIR/bin/python" ]; then
  python -m venv "$VENV_DIR"
fi

PY="$VENV_DIR/bin/python"
"$PY" -m pip install --upgrade pip wheel setuptools
"$PY" -m pip install -r "$REPO_ROOT/birefnet_worker/requirements.txt"

REVISION="$($PY - "$MODEL_ID" <<'PY'
import sys
from huggingface_hub import model_info
model_id = sys.argv[1]
info = model_info(model_id)
if not info.sha:
    raise SystemExit(f"Could not resolve Hugging Face revision for {model_id}")
print(info.sha)
PY
)"

echo "Resolved $MODEL_ID revision: $REVISION"

# Download the model and its trusted remote code now, then force local-only use
# at runtime. Pinning the resolved revision makes later startup reproducible.
"$PY" - "$MODEL_ID" "$REVISION" <<'PY'
import sys
from transformers import AutoModelForImageSegmentation
model_id, revision = sys.argv[1], sys.argv[2]
AutoModelForImageSegmentation.from_pretrained(
    model_id,
    revision=revision,
    trust_remote_code=True,
)
print("BiRefNet model cached locally.")
PY

cat > "$ENV_FILE" <<EOF
# Generated by game_creater/scripts/setup_birefnet_sidecar.sh
BIREFNET_MODEL_ID=$MODEL_ID
BIREFNET_MODEL_REVISION=$REVISION
BIREFNET_DEVICE=$DEVICE
BIREFNET_INPUT_SIZE=$INPUT_SIZE
BIREFNET_LOCAL_FILES_ONLY=1
BIREFNET_MAX_IMAGE_BYTES=20971520
BIREFNET_SIDECAR_HOST=127.0.0.1
BIREFNET_SIDECAR_PORT=8010
BIREFNET_SIDECAR_URL=http://127.0.0.1:8010
BIREFNET_SIDECAR_TIMEOUT=120
BIREFNET_VENV_DIR=$VENV_DIR
GAME_CREATER_EDGE_REFINER=birefnet_sidecar
EOF
chmod 600 "$ENV_FILE"

cat <<EOF

BiRefNet sidecar setup finished.
Environment file:
  $ENV_FILE
Pinned model:
  $MODEL_ID@$REVISION

Start the sidecar:
  bash scripts/start_birefnet_sidecar.sh

Then start/restart the main backend so it sources the BiRefNet env as well.
EOF
