#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python}"
MODELS_ROOT="${GAME_CREATER_MODELS_ROOT:-$HOME/.local/share/game_creater}"
GSAM_ROOT="$MODELS_ROOT/Grounded-SAM-2"
GSAM_REF="${GROUNDED_SAM2_REF:-main}"
ENV_FILE="${GAME_CREATER_ENV_FILE:-$HOME/.config/game_creater/grounded_sam2.env}"
REQUIRE_CUDA="${GAME_CREATER_REQUIRE_CUDA:-1}"

mkdir -p "$MODELS_ROOT" "$(dirname "$ENV_FILE")"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_command git
require_command "$PYTHON_BIN"

"$PYTHON_BIN" - <<'PY'
import sys
if sys.version_info < (3, 10):
    raise SystemExit(f"Python >=3.10 is required, got {sys.version.split()[0]}")
print(f"python={sys.version.split()[0]}")
PY

if ! "$PYTHON_BIN" - <<'PY'
try:
    import torch
    import torchvision
    print(f"torch={torch.__version__}, torchvision={torchvision.__version__}, cuda={torch.cuda.is_available()}, torch_cuda={torch.version.cuda}")
except Exception as exc:
    raise SystemExit(f"PyTorch/TorchVision are not ready: {exc}")
PY
then
  cat >&2 <<'EOF'
Install a CUDA-compatible PyTorch + TorchVision build first, then re-run this script.
Grounded-SAM-2 currently documents Python 3.10, torch >=2.3.1 and torchvision >=0.18.1.
Use the official PyTorch selector so the CUDA runtime matches your machine.
EOF
  exit 1
fi

if [ "$REQUIRE_CUDA" = "1" ]; then
  if ! "$PYTHON_BIN" - <<'PY'
import torch
if not torch.cuda.is_available():
    raise SystemExit("torch.cuda.is_available() is False")
print(torch.cuda.get_device_name(0))
PY
  then
    echo "CUDA is required for the recommended local Grounded-SAM2 setup." >&2
    echo "Set GAME_CREATER_REQUIRE_CUDA=0 only for diagnostic/CPU experiments." >&2
    exit 1
  fi

  if command -v nvidia-smi >/dev/null 2>&1; then
    nvidia-smi --query-gpu=name,driver_version --format=csv,noheader || true
  else
    echo "nvidia-smi not found. In WSL2, confirm the Windows NVIDIA driver exposes the GPU to WSL." >&2
    exit 1
  fi
fi

# GroundingDINO compiles a CUDA Deformable Attention operator. Detect CUDA_HOME
# before installation so a PyTorch-visible GPU does not create a false-ready state.
if [ -z "${CUDA_HOME:-}" ]; then
  CUDA_HOME="$($PYTHON_BIN - <<'PY'
try:
    from torch.utils.cpp_extension import CUDA_HOME
    print(CUDA_HOME or "")
except Exception:
    print("")
PY
)"
fi
if [ -z "${CUDA_HOME:-}" ] && [ -x /usr/local/cuda/bin/nvcc ]; then
  CUDA_HOME=/usr/local/cuda
fi

if [ "$REQUIRE_CUDA" = "1" ]; then
  if [ -z "${CUDA_HOME:-}" ] || [ ! -x "$CUDA_HOME/bin/nvcc" ]; then
    cat >&2 <<'EOF'
CUDA compilation toolkit was not found.
GroundingDINO needs CUDA_HOME and nvcc to build its Deformable Attention operator.
Install the CUDA toolkit inside WSL (not only the Windows display driver), then set for example:
  export CUDA_HOME=/usr/local/cuda
EOF
    exit 1
  fi
  export CUDA_HOME
  export PATH="$CUDA_HOME/bin:$PATH"
  echo "CUDA_HOME=$CUDA_HOME"
  "$CUDA_HOME/bin/nvcc" --version | tail -n 1
fi

if [ ! -d "$GSAM_ROOT/.git" ]; then
  git clone https://github.com/IDEA-Research/Grounded-SAM-2.git "$GSAM_ROOT"
else
  git -C "$GSAM_ROOT" fetch --tags --prune origin
fi

if [ "$GSAM_REF" = "main" ]; then
  git -C "$GSAM_ROOT" checkout main
  git -C "$GSAM_ROOT" pull --ff-only origin main
else
  git -C "$GSAM_ROOT" checkout "$GSAM_REF"
fi
GSAM_COMMIT="$(git -C "$GSAM_ROOT" rev-parse HEAD)"
echo "Grounded-SAM-2 commit=$GSAM_COMMIT"

"$PYTHON_BIN" -m pip install -e "$GSAM_ROOT"
"$PYTHON_BIN" -m pip install --no-build-isolation -e "$GSAM_ROOT/grounding_dino"

SAM2_CHECKPOINT="$GSAM_ROOT/checkpoints/sam2.1_hiera_large.pt"
GDINO_CHECKPOINT="$GSAM_ROOT/gdino_checkpoints/groundingdino_swint_ogc.pth"
GDINO_CONFIG="$GSAM_ROOT/grounding_dino/groundingdino/config/GroundingDINO_SwinT_OGC.py"

if [ ! -s "$SAM2_CHECKPOINT" ]; then
  (cd "$GSAM_ROOT/checkpoints" && bash download_ckpts.sh)
else
  echo "SAM2 checkpoint already exists: $SAM2_CHECKPOINT"
fi

if [ ! -s "$GDINO_CHECKPOINT" ]; then
  (cd "$GSAM_ROOT/gdino_checkpoints" && bash download_ckpts.sh)
else
  echo "GroundingDINO checkpoint already exists: $GDINO_CHECKPOINT"
fi

for required in "$SAM2_CHECKPOINT" "$GDINO_CHECKPOINT" "$GDINO_CONFIG"; do
  if [ ! -s "$required" ]; then
    echo "Required model/config file is missing or empty: $required" >&2
    exit 1
  fi
done

cat > "$ENV_FILE" <<EOF
# Generated by game_creater/scripts/setup_grounded_sam2_wsl.sh
# Grounded-SAM-2 commit: $GSAM_COMMIT
GAME_CREATER_MODE=grounded_sam2_local
GAME_CREATER_DEVICE=auto
GAME_CREATER_BOX_THRESHOLD=0.35
GAME_CREATER_TEXT_THRESHOLD=0.25
GAME_CREATER_DEDUPE_IOU=0.65
GAME_CREATER_CROSS_LABEL_DEDUPE_IOU=0.92
GAME_CREATER_MASK_DEDUPE_IOU=0.86
GAME_CREATER_CROSS_LABEL_MASK_DEDUPE_IOU=0.96
GROUNDING_DINO_CONFIG=$GDINO_CONFIG
GROUNDING_DINO_CHECKPOINT=$GDINO_CHECKPOINT
SAM2_MODEL_CONFIG=configs/sam2.1/sam2.1_hiera_l.yaml
SAM2_CHECKPOINT=$SAM2_CHECKPOINT
CUDA_HOME=${CUDA_HOME:-}
GAME_CREATER_GSAM_COMMIT=$GSAM_COMMIT
EOF

chmod 600 "$ENV_FILE"

echo
"$PYTHON_BIN" "$SCRIPT_DIR/verify_grounded_sam2_env.py" --env-file "$ENV_FILE" $([ "$REQUIRE_CUDA" = "1" ] || printf '%s' '--allow-cpu')

cat <<EOF

Grounded-SAM2 installation finished.
Environment file:
  $ENV_FILE
Grounded-SAM-2 commit:
  $GSAM_COMMIT

Start Game Creater:
  cd "$REPO_ROOT"
  bash scripts/start_grounded_sam2_wsl.sh

Then open from Windows/browser:
  http://127.0.0.1:8000

Model status:
  http://127.0.0.1:8000/api/v1/models/status
EOF
