#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib.util
import os
import shutil
import subprocess
import sys
from pathlib import Path


def _version_tuple(value: str) -> tuple[int, ...]:
    numbers: list[int] = []
    for part in value.split("+")[0].split("."):
        digits = "".join(ch for ch in part if ch.isdigit())
        if not digits:
            break
        numbers.append(int(digits))
    return tuple(numbers)


def _load_env_file(path: Path) -> None:
    if not path.is_file():
        return
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key.strip(), os.path.expandvars(os.path.expanduser(value)))


def _command_output(command: list[str]) -> tuple[bool, str]:
    try:
        result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=15)
    except Exception as exc:
        return False, str(exc)
    output = (result.stdout or result.stderr or "").strip().splitlines()
    return result.returncode == 0, output[0] if output else f"exit={result.returncode}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify Game Creater GroundingDINO + SAM2 local GPU environment")
    parser.add_argument(
        "--env-file",
        default=os.getenv("GAME_CREATER_ENV_FILE", str(Path.home() / ".config/game_creater/grounded_sam2.env")),
        help="Optional shell-style env file generated by setup_grounded_sam2_wsl.sh",
    )
    parser.add_argument("--allow-cpu", action="store_true", help="Do not fail solely because CUDA is unavailable")
    args = parser.parse_args()

    env_file = Path(args.env_file).expanduser()
    _load_env_file(env_file)

    checks: list[tuple[str, bool, str]] = []
    checks.append(("python>=3.10", sys.version_info >= (3, 10), sys.version.split()[0]))

    torch = None
    torchvision = None
    try:
        import torch as imported_torch
        import torchvision as imported_torchvision

        torch = imported_torch
        torchvision = imported_torchvision
        checks.append(("torch>=2.3.1", _version_tuple(torch.__version__) >= (2, 3, 1), torch.__version__))
        checks.append(("torchvision>=0.18.1", _version_tuple(torchvision.__version__) >= (0, 18, 1), torchvision.__version__))
    except Exception as exc:
        checks.append(("torch import", False, str(exc)))

    if torch is not None:
        cuda_available = bool(torch.cuda.is_available())
        checks.append(("torch CUDA", cuda_available or args.allow_cpu, f"available={cuda_available}, build={torch.version.cuda}"))
        if cuda_available:
            try:
                checks.append(("GPU", True, torch.cuda.get_device_name(0)))
            except Exception as exc:
                checks.append(("GPU", False, str(exc)))

    nvidia_smi = shutil.which("nvidia-smi")
    if args.allow_cpu and not nvidia_smi:
        checks.append(("nvidia-smi", True, "not required in --allow-cpu mode"))
    else:
        ok, detail = _command_output([nvidia_smi, "--query-gpu=name,driver_version", "--format=csv,noheader"]) if nvidia_smi else (False, "not found")
        checks.append(("nvidia-smi", ok, detail))

    cuda_home = os.getenv("CUDA_HOME", "").strip()
    if not cuda_home and torch is not None:
        try:
            from torch.utils.cpp_extension import CUDA_HOME as torch_cuda_home

            cuda_home = str(torch_cuda_home or "")
        except Exception:
            pass
    cuda_home_path = Path(cuda_home).expanduser() if cuda_home else None
    nvcc = str(cuda_home_path / "bin/nvcc") if cuda_home_path else shutil.which("nvcc")
    nvcc_exists = bool(nvcc and Path(nvcc).is_file())
    if args.allow_cpu:
        checks.append(("CUDA_HOME/nvcc", True, str(nvcc or cuda_home or "not required in --allow-cpu mode")))
    else:
        checks.append(("CUDA_HOME/nvcc", nvcc_exists, str(nvcc or cuda_home or "not found")))
        if nvcc_exists:
            ok, detail = _command_output([str(nvcc), "--version"])
            checks.append(("nvcc", ok, detail))

    for module_name in ("sam2", "grounding_dino"):
        found = importlib.util.find_spec(module_name) is not None
        checks.append((f"import {module_name}", found, "found" if found else "not found"))

    required_paths = {
        "GroundingDINO config": os.getenv("GROUNDING_DINO_CONFIG", ""),
        "GroundingDINO checkpoint": os.getenv("GROUNDING_DINO_CHECKPOINT", ""),
        "SAM2 checkpoint": os.getenv("SAM2_CHECKPOINT", ""),
    }
    for label, value in required_paths.items():
        path = Path(value).expanduser() if value else None
        checks.append((label, bool(path and path.is_file()), str(path or "unset")))

    sam2_config = os.getenv("SAM2_MODEL_CONFIG", "").strip()
    checks.append(("SAM2 model config", bool(sam2_config), sam2_config or "unset"))

    print(f"env_file={env_file} ({'loaded' if env_file.is_file() else 'not found; using current environment'})")
    print("-" * 72)
    failed = 0
    for name, ok, detail in checks:
        print(f"{'PASS' if ok else 'FAIL':4}  {name:30} {detail}")
        if not ok:
            failed += 1
    print("-" * 72)
    if failed:
        print(f"Environment verification failed: {failed} check(s) need attention.")
        return 1
    print("Environment verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
